name: Update Schedule

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Cache dependencies
        uses: actions/cache@v4.0.0
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.1
        with:
          node-version: "18"

      - name: Update index.html
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          git config --global user.name "tripleseven190504"
          git config --global user.email "tripleseven190504@gmail.com"
          git pull
          npm install
          node index.js

      - name: Set up Git
        if: steps.check_changes.outcome == 'success'
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Cập nhật vào: $(TZ='Asia/Ho_Chi_Minh' date '+%H:%M - %d/%m')" >> index.html
            echo "  " >> index.html
            git add .
            git commit -m "Update index.html" || echo "No changes to commit"
            git push
          else
            echo "No changes detected. Skipping commit and push."
          fi
